# Generated by Django 3.0.5 on 2020-05-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='body',
            field=models.TextField(max_length=140),
        ),
    ]
